name: Push Build to Artifactory    

on: [push]
permissions:
  # This is required for requesting the OIDC token
  id-token: write
  # This is required for actions/checkout
  contents: read

jobs:
 build:
   runs-on: ubuntu-latest
   environment: Dev
  
   steps:
   # This action checks out the code from the repository
   - name: Checkout Code 
     uses: actions/checkout@v4


   - name: Set up JFrog CLI
     id: setup-jfrog-cli
     uses: jfrog/setup-jfrog-cli@v4
       
        
     env:
        JF_URL: ${{ vars.JF_URL }}
     with:
        oidc-provider-name: ap-pypi 


        
   - name: Configure pip client using JFrog CLI with
   
     run: |
       jf c show
       jf rt ping
       jf pip-config --repo-resolve=ap-pypi
       jf pip install pandas
